### ISSUE TITLE
怎么编译呢？

### ISSUE THREAD

**Issue by bnqzzdf** [Cloud-Leung/Jaspersoft_Studio_nl_zh#1]
没有做过相关汉化，想学习一下怎么编译才能使用呢？

**Comment by shichenzhe-p** [comment]
1. 下载git上对应目录的文件。
2. 在本地jaspersoft studio安装根目录/plugins中查找步骤1中指向的对应目录的jar包。
3. 用压缩工具将步骤1下载的文件，放到步骤2中对应的jar包。
4. 重新启动jaspersoft studio。
5. 注意studio的版本，不同版本间翻译内容可能有差异。

**Comment by bnqzzdf** [comment]
非常棒的解答~
